### ISSUE TITLE
Player Movement

### ISSUE THREAD

**Issue by petros-koutsouvelis** [michailmarkou1995/unitytest#10]
We need to make a player controller to allow 2d movement. 
Player should be allowed to:

- [x] Move sideways

- [x] Jump

- [x] Climb(?)

- ~~[ ] Swim~~

- ~~[ ] Fly~~

- [x] The player's speed should slowly ramp up.

**Comment by michailmarkou1995** [comment]
Swim and Fly must be added @petros-koutsouvelis
