### ISSUE TITLE
Test Scene Creation

### ISSUE THREAD

**Issue by petros-koutsouvelis** [michailmarkou1995/unitytest#3]
We need to make a scene in unity to test the main character's movements

The map includes?: (mark as a tick when done) 

- [x] Enemy/ies

- [x] Gaps to void (player to fall into)

- [x] User Interface (Timer, Lives, Coin tracker)

- [x] Player movement (jump & back and forth)

- [x] The player Camera is forbidden to go back if you miss a coin

- [x] Coins on land

- [x] Coins are hidden on boxes (jump n hit to reveal them)

**Comment by michailmarkou1995** [comment]
The map includes?: 

- Enemy/ies
- Gaps to void (player to fall into)
- Timer
- Player movement (jump & back and forth)
- The player Camera is forbidden to go back if you miss a coin
- Coins on land
- Coins are hidden on boxes (jump n hit to reveal them)

**Comment by Dr1nkBearzZ** [comment]
prospa8isa na dimiourgiso mia apli parastasi kiniseon se piramatika koutakia mexri na paroume ta assets episis ebala rigidbody sta game object(antimetopisa kapia problimata me to na kalo function se alla scripts)

**Comment by petros-koutsouvelis** [comment]
Added a timer GUI element inside the testLevel scene with it's corresponding script inside the Scripts folder
